export const ROOM_STATUS = {
  LOBBY: "lobby",
  IN_ROUND: "in_round",
  FINAL_VOTING: "final_voting",
  ENDED: "ended"
};

export const DEFAULT_SETTINGS = {
  maxPlayers: 10,
  totalRounds: 3,
  category: "random",
  gameMode: "online",
  votingTimeSeconds: 60,
  numberOfImposters: 1
};

export const WORD_BANK = {
  general: [
    "Air Fryer",
    "Backpack",
    "Barcode",
    "Coffee",
    "Fireworks",
    "Headphones",
    "Hoodie",
    "Keyboard",
    "Lighthouse",
    "Microwave",
    "Mirror",
    "Passport",
    "Rainstorm",
    "Sunglasses",
    "Toothbrush"
  ],
  movies: [
    "Barbie",
    "Dune",
    "Godzilla",
    "Gladiator",
    "Inception",
    "Interstellar",
    "Joker",
    "Kung Fu Panda",
    "Minions",
    "Oppenheimer",
    "Spider-Verse",
    "Titanic",
    "Top Gun",
    "Wakanda",
    "Wonka"
  ],
  animals: [
    "Axolotl",
    "Cheetah",
    "Dolphin",
    "Falcon",
    "Flamingo",
    "Giraffe",
    "Koala",
    "Octopus",
    "Otter",
    "Panda",
    "Penguin",
    "Sloth",
    "Tiger",
    "Wolf",
    "Zebra"
  ],
  travel: [
    "Airport",
    "Backpacking",
    "Beach",
    "Boarding Pass",
    "Cruise",
    "Hostel",
    "Itinerary",
    "Metro",
    "Mountain",
    "Road Trip",
    "Suitcase",
    "Temple",
    "Train",
    "Visa",
    "Waterfall"
  ],
  food: [
    "Avocado Toast",
    "Boba",
    "Burrito",
    "Croissant",
    "Dumpling",
    "Hotpot",
    "Ice Cream",
    "Nachos",
    "Pancakes",
    "Pasta",
    "Ramen",
    "Samosa",
    "Sushi",
    "Taco",
    "Waffles"
  ],
  sports: [
    "Badminton",
    "Basketball",
    "Cricket",
    "Formula One",
    "Goalkeeper",
    "Marathon",
    "Penalty Kick",
    "Pickleball",
    "Skateboard",
    "Snowboarding",
    "Surfing",
    "Tennis",
    "Touchdown",
    "Volleyball",
    "World Cup"
  ],
  gaming: [
    "Battle Royale",
    "Boss Fight",
    "Checkpoint",
    "Controller",
    "Crafting",
    "Dungeon",
    "Elden Ring",
    "Fortnite",
    "Minecraft",
    "NPC",
    "PlayStation",
    "Power-Up",
    "Speedrun",
    "Valorant",
    "XP"
  ],
  internet: [
    "Algorithm",
    "Emoji",
    "GIF",
    "Hashtag",
    "Livestream",
    "Meme",
    "Notification",
    "Podcast",
    "QR Code",
    "Reel",
    "Screenshot",
    "Story",
    "Thumbnail",
    "Trending",
    "Viral"
  ],
  music: [
    "Acoustic",
    "Album",
    "Beat Drop",
    "Chorus",
    "DJ",
    "Drumline",
    "Encore",
    "Festival",
    "Guitar Solo",
    "Headliner",
    "K-Pop",
    "Mixtape",
    "Playlist",
    "Rap",
    "Vinyl"
  ],
  tech: [
    "AI",
    "Bluetooth",
    "Cloud",
    "Cybersecurity",
    "Drone",
    "Electric Car",
    "Foldable Phone",
    "Keyboard",
    "Neural Network",
    "Robot",
    "Smartwatch",
    "Startup",
    "Touchscreen",
    "USB-C",
    "VR"
  ],
  pop_culture: [
    "Anime",
    "Cosplay",
    "Fandom",
    "Influencer",
    "K-Drama",
    "Merch",
    "Met Gala",
    "Red Carpet",
    "Remix",
    "Reality Show",
    "Spoiler",
    "Stan",
    "Streaming",
    "Superhero",
    "Trailer"
  ],
  random: []
};
